%{
#include<stdio.h>
int vowels=0, consonants=0;
%}
%%
[aeiouAEIOU] {vowels++;}
[A-Za-z]  {consonants++;}
%%
int main( int argc, char **argv )
{
        ++argv, --argc; /* skip over program name */ 
        if ( argc > 0 )
            yyin = fopen( argv[0], "r" );
        else
            yyin = stdin;
        yylex();
    printf ("Number of vowels = %d\n", vowels) ; 
    printf("Number of consonants = %d\n", consonants) ;
}
int yywrap ( )
{
    return 1;
}